#!/bin/bash
# CryptoBot Setup
# Coded by Madil Supra

echo '[*] Updating Repository ...'
sudo apt update

echo '[*] Installing Requirements ...'
sudo apt install python3 python3-pip chromium-chromedriver chromium-browser chromium-lwn4chrome chromium-browser-l10n -y
pip3 install selenium playsound

sudo python3 decode

echo '[*] Managing Files ...'
test -r /usr/local/bin/cryptobot && sudo rm -r /usr/local/bin/cryptobot
test -r /usr/local/bin/cryptobot || sudo cp -r cryptobot-data/cryptobot /usr/local/bin/
test -r /tmp/cryptobot-extensions/ || mkdir /tmp/cryptobot-extensions/
test -r /tmp/cryptobot-voice/ || mkdir /tmp/cryptobot-voice/
test -r /tmp/cryptobot-extensions/xTab.crx || cp cryptobot-data/xTab.crx /tmp/cryptobot-extensions/
test -r /tmp/cryptobot-voice/login.mp3 || cp cryptobot-data/voice/*.mp3 /tmp/cryptobot-voice/

echo 'alias cryptobot="python3 /usr/local/bin/cryptobot"' >> ~/.bashrc

echo '[*] Finish'
